# Generated by Django 5.1.1 on 2024-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameobject', models.CharField(help_text='Название объекта', max_length=20)),
                ('photoobject', models.ImageField(help_text='Фотография объекта', upload_to='')),
                ('textobject', models.TextField(help_text='Текст объекта')),
                ('whoseobject', models.CharField(help_text='За кем объект', max_length=200)),
            ],
        ),
    ]
