# Generated by Django 5.1.1 on 2024-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
