# Generated by Django 5.1.1 on 2024-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_catalog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
