# Generated by Django 5.1.1 on 2024-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_catalog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='city',
            field=models.CharField(default=None, help_text='Местоположение объекта', max_length=20),
        ),
        migrations.AddField(
            model_name='catalog',
            name='type',
            field=models.CharField(default=None, help_text='Тип объекта', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photoobject',
            field=models.ImageField(help_text='Фотография объекта', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='whoseobject',
            field=models.CharField(help_text='За кем объект', max_length=20),
        ),
    ]
