# Generated by Django 5.1.1 on 2024-10-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_catalog_city_catalog_type_alter_catalog_photoobject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='photoobject',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user.catalog')),
            ],
        ),
    ]
