# Generated by Django 5.1.1 on 2024-10-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_catalog_photoobject_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='date',
            field=models.DateField(),
        ),
    ]
